# https://docs.microsoft.com/azure/devops/pipelines/languages/python
pool:
  vmImage: 'ubuntu-16.04' # other options: 'macOS-10.13', 'vs2017-win2016'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'

#steps2:
#  - task: UsePythonVersion@0
#    versionSpec: '3.6'
#
#  - script: pipenv sync
