# https://docs.microsoft.com/azure/devops/pipelines/languages/python
pool:
  vmImage: ubuntu-16.04

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7.x'

  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add miniconda binaries to PATH

  - script: pipenv sync
